### PR TITLE
CLI:apply: call udevadm trigger, using --action=move (Closes: #1071220) (LP: #2066344, LP: #2071363)

### PR DESCRIPTION
**Pull request by slyon**
## Description
CLI:apply: call udevadm trigger, using --action=add (Closes: #1071220)
    
This will (re)-apply .link files, e.g. to set offloading options

As per discussion in [Debian#1071220](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1071220):

Yu says:

> https://github.com/canonical/netplan/blob/26d2591d771cb4343c06dbb1e0eb1f3587ec910d/netplan_cli/cli/commands/apply.py#L257
> 
> Here, "--action add" is necessary, otherwise the generated .link
> files will be never applied to existing interfaces.

## Checklist

- [ ] Runs `make check` successfully.
- [ ] Retains 100% code coverage (`make check-coverage`).
- [ ] New/changed keys in YAML format are documented.
- [ ] \(Optional\) Adds example YAML for new feature.
- [x] \(Optional\) Closes an open bug in Launchpad. LP#2066344

### CODE REVIEW

**Comment by slyon** [comment]
This is most probably related to https://github.com/systemd/systemd/pull/31998 which changes the behavior of `udevadm test-builtint net_setup_link /sys/class/net/...` and `udevadm test /sys/class/net/...` which Netplan had been relying on.

This will not apply actual ethtool settings to the device for us any more.

**Comment by slyon** [comment]
See https://salsa.debian.org/debian/netplan.io/-/pipelines/686650 for DebCI (unstable) testing results.

**Comment by slyon** [comment]
This seems to FTBFS now on unstable, for unrelated(?) reason:

```
================================================= test session starts =================================================
platform linux -- Python 3.11.9, pytest-8.2.2, pluggy-1.5.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /build/netplan.io-GpU4qN/netplan.io-1.0
plugins: cov-5.0.0
collected 25 items                                                                                                    

tests/netplan_dbus/test_dbus.py::TestNetplanDBus::test_netplan_apply_in_snap_calls_busctl PASSED
tests/netplan_dbus/test_dbus.py::TestNetplanDBus::test_netplan_apply_in_snap_calls_busctl_err PASSED
tests/netplan_dbus/test_dbus.py::TestNetplanDBus::test_netplan_apply_in_snap_calls_busctl_ret130 PASSED
tests/netplan_dbus/test_dbus.py::TestNetplanDBus::test_netplan_apply_in_snap_uses_dbus PASSED
tests/netplan_dbus/test_dbus.py::TestNetplanDBus::test_netplan_dbus_config PASSED
tests/netplan_dbus/test_dbus.py::TestNetplanDBus::test_netplan_dbus_config_apply PASSED
tests/netplan_dbus/test_dbus.py::TestNetplanDBus::test_netplan_dbus_config_cancel PASSED
tests/netplan_dbus/test_dbus.py::TestNetplanDBus::test_netplan_dbus_config_get PASSED
tests/netplan_dbus/test_dbus.py::TestNetplanDBus::test_netplan_dbus_config_set PASSED
tests/netplan_dbus/test_dbus.py::TestNetplanDBus::test_netplan_dbus_config_set_invalidate PASSED
tests/netplan_dbus/test_dbus.py::TestNetplanDBus::test_netplan_dbus_config_set_uninvalidate PASSED
tests/netplan_dbus/test_dbus.py::TestNetplanDBus::test_netplan_dbus_config_set_uninvalidate_timeout PASSED
tests/netplan_dbus/test_dbus.py::TestNetplanDBus::test_netplan_dbus_config_try_apply PASSED
tests/netplan_dbus/test_dbus.py::TestNetplanDBus::test_netplan_dbus_config_try_cancel PASSED
tests/netplan_dbus/test_dbus.py::TestNetplanDBus::test_netplan_dbus_config_try_cb PASSED
tests/netplan_dbus/test_dbus.py::TestNetplanDBus::test_netplan_dbus_config_try_config_try PASSED
tests/netplan_dbus/test_dbus.py::TestNetplanDBus::test_netplan_dbus_config_try_no_ready_signal PASSED
tests/netplan_dbus/test_dbus.py::TestNetplanDBus::test_netplan_dbus_generate PASSED
tests/netplan_dbus/test_dbus.py::TestNetplanDBus::test_netplan_dbus_happy PASSED
tests/netplan_dbus/test_dbus.py::TestNetplanDBus::test_netplan_dbus_info PASSED
tests/netplan_dbus/test_dbus.py::TestNetplanDBus::test_netplan_dbus_no_such_command PASSED
tests/netplan_dbus/test_dbus.py::TestNetplanDBus::test_netplan_dbus_noroot PASSED
tests/netplan_dbus/test_dbus.py::TestNetplanDBus::test_netplan_generate_in_snap_calls_busctl PASSED
tests/netplan_dbus/test_dbus.py::TestNetplanDBus::test_netplan_generate_in_snap_calls_busctl_err PASSED
tests/netplan_dbus/test_dbus.py::TestNetplanDBus::test_netplan_generate_in_snap_calls_busctl_ret130 PASSED
tests/netplan_dbus/test_dbus.py::TestNetplanDBus::test_netplan_generate_in_snap_calls_busctl_ret130 ERROR

======================================================= ERRORS ========================================================
_______________ ERROR at teardown of TestNetplanDBus.test_netplan_generate_in_snap_calls_busctl_ret130 ________________
/usr/lib/python3.11/shutil.py:742: in rmtree
    onerror(os.lstat, path, sys.exc_info())
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

path = '/tmp/tmpz04xshk5/run/netplan/config-DNE8O2', ignore_errors = False
onerror = <function rmtree.<locals>.onerror at 0x71dd064a4040>

    def rmtree(path, ignore_errors=False, onerror=None, *, dir_fd=None):
        """Recursively delete a directory tree.
    
        If dir_fd is not None, it should be a file descriptor open to a directory;
        path will then be relative to that directory.
        dir_fd may not be implemented on your platform.
        If it is unavailable, using it will raise a NotImplementedError.
    
        If ignore_errors is set, errors are ignored; otherwise, if onerror
        is set, it is called to handle the error with arguments (func,
        path, exc_info) where func is platform and implementation dependent;
        path is the argument to that function that caused it to fail; and
        exc_info is a tuple returned by sys.exc_info().  If ignore_errors
        is false and onerror is None, an exception is raised.
    
        """
        sys.audit("shutil.rmtree", path, dir_fd)
        if ignore_errors:
            def onerror(*args):
                pass
        elif onerror is None:
            def onerror(*args):
                raise
        if _use_fd_functions:
            # While the unsafe rmtree works fine on bytes, the fd based does not.
            if isinstance(path, bytes):
                path = os.fsdecode(path)
            # Note: To guard against symlink races, we use the standard
            # lstat()/open()/fstat() trick.
            try:
>               orig_st = os.lstat(path, dir_fd=dir_fd)
E               FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpz04xshk5/run/netplan/config-DNE8O2'

/usr/lib/python3.11/shutil.py:740: FileNotFoundError
=============================================== short test summary info ===============================================
ERROR tests/netplan_dbus/test_dbus.py::TestNetplanDBus::test_netplan_generate_in_snap_calls_busctl_ret130 - FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpz04xshk5/run/netplan/config-DNE8O2'
============================================ 25 passed, 1 error in 43.02s =============================================
```

**Comment by daniloegea** [comment]
This seems to fix the issue we were facing.

I'm not an expert on systemd/udev so I was wondering what side effects it could cause. Like, does this change affect external interfaces managed by services like docker or any kubernetes CNI for example...

We might want to be more specific in the udev trigger action and match only interfaces managed with netplan. There is this TAG property we could try to use https://www.freedesktop.org/software/systemd/man/latest/udev.html#TAG1

We could add the tag "netplan" when generating the udev rules and add the `--tag-match=netplan` to the command.

I haven't tested it so I'm not really sure it would work well.

**Comment by slyon** [comment]
Enabling debug logging in systemd-udevd I can especially see this log message:
`enp5s0: Not applying .link settings on 'change' uevent.`

Which points to this commit specifically: https://github.com/systemd/systemd/commit/0c3af33e19b5f74dbb893aca12946a4d4935a917
Looks like `ethtool` settings (like to offloading bits) are only applied for ADD, BIND, or MOVE events on systemd v256+, not on CHANGE events any more, as it used to be previously.

Full log:
```
Jul 03 12:56:17 oo-vm systemd-udevd[394]: Reading rules file: /usr/lib/udev/rules.d/77-mm-telit-port-types.rules
Jul 03 12:56:17 oo-vm systemd-udevd[394]: Reading rules file: /usr/lib/udev/rules.d/77-mm-tplink-port-types.rules
Jul 03 12:56:17 oo-vm systemd-udevd[394]: Reading rules file: /usr/lib/udev/rules.d/77-mm-ublox-port-types.rules
Jul 03 12:56:17 oo-vm systemd-udevd[394]: Reading rules file: /usr/lib/udev/rules.d/77-mm-x22x-port-types.rules
Jul 03 12:56:17 oo-vm systemd-udevd[394]: Reading rules file: /usr/lib/udev/rules.d/77-mm-zte-port-types.rules
Jul 03 12:56:17 oo-vm systemd-udevd[394]: Reading rules file: /usr/lib/udev/rules.d/78-graphics-card.rules
Jul 03 12:56:17 oo-vm systemd-udevd[394]: Reading rules file: /usr/lib/udev/rules.d/78-sound-card.rules
Jul 03 12:56:17 oo-vm systemd-udevd[394]: Reading rules file: /usr/lib/udev/rules.d/80-debian-compat.rules
Jul 03 12:56:17 oo-vm systemd-udevd[394]: Reading rules file: /usr/lib/udev/rules.d/80-drivers.rules
Jul 03 12:56:17 oo-vm systemd-udevd[394]: Reading rules file: /usr/lib/udev/rules.d/80-mm-candidate.rules
Jul 03 12:56:17 oo-vm systemd-udevd[394]: Reading rules file: /usr/lib/udev/rules.d/80-net-setup-link.rules
Jul 03 12:56:17 oo-vm systemd-udevd[394]: Reading rules file: /usr/lib/udev/rules.d/80-udisks2.rules
Jul 03 12:56:17 oo-vm systemd-udevd[394]: Reading rules file: /usr/lib/udev/rules.d/81-net-dhcp.rules
Jul 03 12:56:17 oo-vm systemd-udevd[394]: Reading rules file: /usr/lib/udev/rules.d/85-hdparm.rules
Jul 03 12:56:17 oo-vm systemd-udevd[394]: Reading rules file: /usr/lib/udev/rules.d/90-bolt.rules
Jul 03 12:56:17 oo-vm systemd-udevd[394]: Reading rules file: /usr/lib/udev/rules.d/90-console-setup.rules
Jul 03 12:56:17 oo-vm systemd-udevd[394]: Reading rules file: /usr/lib/udev/rules.d/90-fwupd-devices.rules
Jul 03 12:56:17 oo-vm systemd-udevd[394]: Reading rules file: /usr/lib/udev/rules.d/90-iocost.rules
Jul 03 12:56:17 oo-vm systemd-udevd[394]: Reading rules file: /run/udev/rules.d/90-netplan.rules
Jul 03 12:56:17 oo-vm systemd-udevd[394]: Reading rules file: /usr/lib/udev/rules.d/95-dm-notify.rules
Jul 03 12:56:17 oo-vm systemd-udevd[394]: Reading rules file: /usr/lib/udev/rules.d/95-kpartx.rules
Jul 03 12:56:17 oo-vm systemd-udevd[394]: Reading rules file: /usr/lib/udev/rules.d/96-e2scrub.rules
Jul 03 12:56:17 oo-vm systemd-udevd[394]: Reading rules file: /usr/lib/udev/rules.d/99-lxd-agent.rules
Jul 03 12:56:17 oo-vm systemd-udevd[394]: Reading rules file: /usr/lib/udev/rules.d/99-systemd.rules
Jul 03 12:56:17 oo-vm systemd-udevd[394]: Reading rules file: /usr/lib/udev/rules.d/99-vmware-scsi-udev.rules
Jul 03 12:56:18 oo-vm systemd-udevd[394]: enp5s0: Device is queued (SEQNUM=3129, ACTION=change)
Jul 03 12:56:18 oo-vm systemd-udevd[394]: enp5s0: Device ready for processing (SEQNUM=3129, ACTION=change)
Jul 03 12:56:18 oo-vm systemd-udevd[394]: Successfully forked off '(udev-worker)' as PID 993.
Jul 03 12:56:18 oo-vm systemd-udevd[394]: enp5s0: Worker [993] is forked for processing SEQNUM=3129.
Jul 03 12:56:18 oo-vm (udev-worker)[993]: enp5s0: Processing device (SEQNUM=3129, ACTION=change)
Jul 03 12:56:18 oo-vm (udev-worker)[993]: enp5s0: sd-device: Created database file '/run/udev/data/n2' for '/devices/p>
Jul 03 12:56:18 oo-vm (udev-worker)[993]: value '[dmi/id]sys_vendor' is 'QEMU'
Jul 03 12:56:18 oo-vm (udev-worker)[993]: value '[dmi/id]sys_vendor' is 'QEMU'
Jul 03 12:56:18 oo-vm (udev-worker)[993]: enp5s0: /usr/lib/udev/rules.d/50-udev-default.rules:31 Importing properties >
Jul 03 12:56:18 oo-vm (udev-worker)[993]: enp5s0: /usr/lib/udev/rules.d/75-net-description.rules:6 Importing propertie>
Jul 03 12:56:18 oo-vm (udev-worker)[993]: enp5s0: No entry found from hwdb.
Jul 03 12:56:18 oo-vm (udev-worker)[993]: enp5s0: /usr/lib/udev/rules.d/75-net-description.rules:6 Failed to run built>
Jul 03 12:56:18 oo-vm (udev-worker)[993]: enp5s0: /usr/lib/udev/rules.d/75-net-description.rules:8 Importing propertie>
Jul 03 12:56:18 oo-vm systemd-udevd[394]: lo: Device is queued (SEQNUM=3130, ACTION=change)
Jul 03 12:56:18 oo-vm systemd-udevd[394]: lo: Device ready for processing (SEQNUM=3130, ACTION=change)
Jul 03 12:56:18 oo-vm systemd-udevd[394]: Successfully forked off '(udev-worker)' as PID 995.
Jul 03 12:56:18 oo-vm systemd-udevd[394]: lo: Worker [995] is forked for processing SEQNUM=3130.
Jul 03 12:56:18 oo-vm systemd-udevd[394]: Received udev control message (PING)
Jul 03 12:56:18 oo-vm (udev-worker)[995]: lo: Processing device (SEQNUM=3130, ACTION=change)
Jul 03 12:56:18 oo-vm (udev-worker)[995]: lo: sd-device: Created database file '/run/udev/data/n1' for '/devices/virtu>
Jul 03 12:56:18 oo-vm (udev-worker)[995]: value '[dmi/id]sys_vendor' is 'QEMU'
Jul 03 12:56:18 oo-vm (udev-worker)[995]: value '[dmi/id]sys_vendor' is 'QEMU'
Jul 03 12:56:18 oo-vm (udev-worker)[995]: lo: /usr/lib/udev/rules.d/50-udev-default.rules:31 Importing properties from>
Jul 03 12:56:18 oo-vm (udev-worker)[995]: lo: Querying driver name via ethtool API is not supported by device 'lo', ig>
Jul 03 12:56:18 oo-vm (udev-worker)[995]: lo: /usr/lib/udev/rules.d/75-net-description.rules:6 Importing properties fr>
Jul 03 12:56:18 oo-vm (udev-worker)[995]: lo: No entry found from hwdb.
Jul 03 12:56:18 oo-vm (udev-worker)[995]: lo: /usr/lib/udev/rules.d/75-net-description.rules:6 Failed to run builtin '>
Jul 03 12:56:18 oo-vm (udev-worker)[995]: lo: /usr/lib/udev/rules.d/75-net-description.rules:8 Importing properties fr>
Jul 03 12:56:18 oo-vm (udev-worker)[995]: lo: Failed to determine prefix for network interface naming, ignoring: Opera>
Jul 03 12:56:18 oo-vm (udev-worker)[995]: lo: /usr/lib/udev/rules.d/80-net-setup-link.rules:5 Importing properties fro>
Jul 03 12:56:18 oo-vm (udev-worker)[995]: lo: /usr/lib/udev/rules.d/80-net-setup-link.rules:5 Failed to run builtin 'p>
Jul 03 12:56:18 oo-vm (udev-worker)[995]: lo: /usr/lib/udev/rules.d/80-net-setup-link.rules:9 Importing properties fro>
Jul 03 12:56:18 oo-vm (udev-worker)[995]: lo: Not applying .link settings on 'change' uevent.
Jul 03 12:56:18 oo-vm (udev-worker)[995]: lo: /usr/lib/udev/rules.d/80-net-setup-link.rules:11 NAME 'lo'
Jul 03 12:56:18 oo-vm (udev-worker)[995]: lo: sd-device: Created database file '/run/udev/data/n1' for '/devices/virtu>
Jul 03 12:56:18 oo-vm (udev-worker)[995]: lo: sd-device: Created database file '/run/udev/data/n1' for '/devices/virtu>
Jul 03 12:56:18 oo-vm (udev-worker)[995]: lo: Device processed (SEQNUM=3130, ACTION=change)
Jul 03 12:56:18 oo-vm (udev-worker)[995]: lo: sd-device-monitor(worker): Passed 230 byte to netlink monitor.
Jul 03 12:56:18 oo-vm (udev-worker)[993]: enp5s0: MAC address identifier: hw_addr=00:16:3e:77:21:d0 → x00163e7721d0
Jul 03 12:56:18 oo-vm (udev-worker)[993]: sd-device: Failed to chase symlinks in "/sys/devices/pci0000:00/0000:00:01.4>
Jul 03 12:56:18 oo-vm (udev-worker)[993]: virtio10: Failed to get 'of_node' child device: No such device
Jul 03 12:56:18 oo-vm (udev-worker)[993]: sd-device: Failed to chase symlinks in "/sys/devices/pci0000:00/0000:00:01.4>
Jul 03 12:56:18 oo-vm (udev-worker)[993]: 0000:05:00.0: Failed to get PCI onboard label: No such file or directory
Jul 03 12:56:18 oo-vm (udev-worker)[993]: 0000:05:00.0: Could not obtain onboard index: No such file or directory
Jul 03 12:56:18 oo-vm (udev-worker)[993]: enp5s0: PCI path identifier: domain=n/a bus_and_slot=p5s0 func=n/a port=n/a >
Jul 03 12:56:18 oo-vm (udev-worker)[993]: enp5s0: Could not find usb parent device: No such file or directory
Jul 03 12:56:18 oo-vm (udev-worker)[993]: enp5s0: Could not get bcma parent device: No such file or directory
Jul 03 12:56:18 oo-vm (udev-worker)[993]: enp5s0: /usr/lib/udev/rules.d/75-net-description.rules:14 Importing properti>
Jul 03 12:56:18 oo-vm (udev-worker)[993]: enp5s0: hwdb modalias key: "pci:v00001AF4d00001041sv00001AF4sd00001100bc02sc>
Jul 03 12:56:18 oo-vm (udev-worker)[993]: enp5s0: /usr/lib/udev/rules.d/80-net-setup-link.rules:5 Importing properties>
Jul 03 12:56:18 oo-vm (udev-worker)[993]: enp5s0: /usr/lib/udev/rules.d/80-net-setup-link.rules:9 Importing properties>
Jul 03 12:56:18 oo-vm (udev-worker)[993]: enp5s0: Not applying .link settings on 'change' uevent.
Jul 03 12:56:18 oo-vm (udev-worker)[993]: enp5s0: /usr/lib/udev/rules.d/80-net-setup-link.rules:11 NAME 'enp5s0'
Jul 03 12:56:18 oo-vm (udev-worker)[993]: enp5s0: sd-device: Created database file '/run/udev/data/n2' for '/devices/p>
Jul 03 12:56:18 oo-vm (udev-worker)[993]: enp5s0: sd-device: Created database file '/run/udev/data/n2' for '/devices/p>
Jul 03 12:56:18 oo-vm (udev-worker)[993]: enp5s0: Device processed (SEQNUM=3129, ACTION=change)
Jul 03 12:56:18 oo-vm (udev-worker)[993]: enp5s0: sd-device-monitor(worker): Passed 870 byte to netlink monitor.
Jul 03 12:56:18 oo-vm systemd-udevd[394]: No events are queued, removing /run/udev/queue.
Jul 03 12:56:21 oo-vm systemd-udevd[394]: Cleanup idle workers
Jul 03 12:56:21 oo-vm systemd-udevd[394]: Worker [993] exited.
```

**Comment by slyon** [comment]
Upstream bug filed: https://github.com/systemd/systemd/issues/33619

**Comment by slyon** [comment]
Using `--action=move` seems to resolve LP#2071363, while also passing tests around LP#2066344.

> Thanks for the work here. I can confirm that netplan.io 1.0.1-1ubuntu1 triggers the following udev events while `netplan apply` which fixes the issue:
> 
> KERNEL[318.736089] move /devices/pci0000:00/0000:00:05.0/net/ens5 (net)
> KERNEL[318.736131] move /devices/virtual/net/lo (net)
> UDEV [318.738939] move /devices/virtual/net/lo (net)
> UDEV [318.740502] move /devices/pci0000:00/0000:00:05.0/net/ens5 (net)

 (https://bugs.launchpad.net/ubuntu/+source/cloud-init/+bug/2071363/comments/6)

**Comment by slyon** [comment]
No news from the upstream bug report, but it seems to be working as intended for version `1.0.1-1` in Debian unstable+testing and Ubuntu Oracular. No further side-effects observed.

IMO this should be ready for merging. @daniloegea WDYT?

**Comment by daniloegea** [comment]
Cool it fixes the issue and the reported side effect is resolved.

**Review by daniloegea — APPROVED** [review]

**Pull request merged**
