### PR TITLE
Prevent duplicate ARPIPTargets in NetDev files (LP: #1915837)

### PR DESCRIPTION
**Pull request by kivancsunkar**
…(LP: #1915837)

https://bugs.launchpad.net/netplan/+bug/1915837

## Description

Using arp-ip-targets as below is generating 10-netplan-bond0.netdev file which contains ARPIPTargets property with duplicated values;

> arp-ip-targets:
>         - 10.10.10.10
>         - 20.20.20.20

> ARPIPTargets=10.10.10.10 20.20.20.20 10.10.10.10 20.20.20.20

Duplicate values in ARPIPTargets prevents systemd-networkd to process the netdev file due to a validation error in Ubuntu 18.04LTS.

## Checklist

- [x] Runs `make check` successfully.
- [ ] Retains 100% code coverage (`make check-coverage`).
- [ ] New/changed keys in YAML format are documented.
- [ ] \(Optional\) Adds example YAML for new feature.
- [x] \(Optional\) Closes an open bug in Launchpad: https://bugs.launchpad.net/netplan/+bug/1915837

### CODE REVIEW

**Review by slyon — CHANGES_REQUESTED** [review]
Hello @kivancsunkar thank you very much for working on this and for your contribution to the Netplan.io project!

This PR looks good to me from a code point-of-view. But it introduces a reduction of test coverage (`make check-coverage`), as you can see here: https://app.codecov.io/gh/canonical/netplan/compare/199/diff (lines 1635-1635 are not covered by any test). Which means there is no test checking the case of multiple ARPIPTargets in NetDev files with more than one parsing pass.

Could you please add a new test case (e.g. in `tests/generator/test_common.py`) triggering this case, so we can have it covered and tested in our testsuite? This would most probably be a similar test case to `test_eth_address_option_multi_pass` from https://github.com/canonical/netplan/blob/master/tests/generator/test_common.py#L360

I'm looking forward to your update!
Thanks, Lukas

**Comment by kivancsunkar** [comment]
Hi @slyon,

I tried my best to add a test case to the test suite for this case and then improved it to trigger a multiple pass on the YAML configuration. As far as I can tell from the local "make check-coverage" result (after I installed python3-nose package on my test environment), it was a successful test case as intended. However, the final commit haven't triggered a Codecov report yet.

Please let me know if you see room for improvement.

Thanks,
Kivanc

**Comment by slyon** [comment]
Yes, this is looking good! I re-triggered the Github Action to run the coverage check again, something must have gone wrong there. It now shows a diff coverage of 100%, congrats!

Your test seems rather big, though. I think if we'd get rid of the `bond1`, `eno2` and `eno50` (and maybe even `eno49`?) definitions completely (but keeping `bonds` definition before `ethernets`, to trigger multi pass parsing), it should still run the same code path, but the test would be much smaller. Could you please improve this?

Afterwards I'm +1 on merging it!

**Comment by kivancsunkar** [comment]
I updated the test case according to your feedback, thanks 👍

**Review by slyon — APPROVED** [review]
Thank you very much for your contribution :-)

LGTM!

**Pull request merged**
